"""Private file storage helpers (spec/backend.md B4).

Original bytes are addressed by a generated storage key under
``settings.file_storage_root``, never by the client-supplied filename. The
actual MIME type is sniffed from content signatures ("magic bytes") because the
client-declared ``Content-Type`` header is untrusted input (B4, B9).
"""

from __future__ import annotations

import hashlib
import re
import unicodedata
import uuid
from pathlib import Path

#: Supported MIME types (spec/backend.md B4). Kept local to avoid importing
#: ``app.config`` into a pure-IO module; ``app.config.SUPPORTED_MIME_TYPES`` is
#: the single source of truth callers should validate against.
PDF_MAGIC = b"%PDF-"
JPEG_MAGIC = b"\xff\xd8\xff"
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"

#: Longest signature checked, so callers know how many leading bytes to read.
MAGIC_SNIFF_BYTES = 16

#: Fallback display name when sanitization empties the client-supplied name.
DEFAULT_DISPLAY_NAME = "document"

#: Maximum length of a stored display name (matches ``Document.display_name``).
MAX_DISPLAY_NAME_LENGTH = 255


def sniff_mime_type(head: bytes) -> str | None:
    """Return the MIME type implied by ``head``'s content signature, or ``None``.

    Only the leading bytes are needed, so callers can sniff before reading the
    full upload. Never trusts the client's ``Content-Type`` header (B4, B9).
    """
    if head.startswith(PDF_MAGIC):
        return "application/pdf"
    if head.startswith(JPEG_MAGIC):
        return "image/jpeg"
    if head.startswith(PNG_MAGIC):
        return "image/png"
    return None


def sanitize_display_name(raw_name: str | None) -> str:
    """Strip path components and control characters from a client filename.

    The sanitized value is stored only for display; it is never used to build a
    filesystem path (B4). Path separators from either OS convention are removed,
    control characters are dropped and the result is bounded in length.
    """
    name = raw_name or ""
    # Strip any leading path components a browser or proxy might have left in
    # (both POSIX and Windows separators), then take only the final segment.
    name = name.replace("\\", "/").rsplit("/", 1)[-1]
    # Drop control characters (including NUL) and normalize combining forms.
    name = unicodedata.normalize("NFC", name)
    name = "".join(ch for ch in name if unicodedata.category(ch)[0] != "C")
    name = name.strip().strip(".")
    name = re.sub(r"\s+", " ", name)
    if not name:
        return DEFAULT_DISPLAY_NAME
    return name[:MAX_DISPLAY_NAME_LENGTH]


def new_storage_key(case_id: str, extension: str) -> str:
    """Return a fresh, unguessable relative storage key for one upload.

    Keys are namespaced by case so a directory listing of the private root
    cannot be trivially correlated across cases, and are never derived from the
    client filename (B4).
    """
    token = uuid.uuid4().hex
    suffix = f".{extension}" if extension else ""
    return f"documents/{case_id}/{token}{suffix}"


def new_image_key(case_id: str, document_id: str, page_number: int) -> str:
    """Return a storage key for a rendered page image (B4)."""
    return f"pages/{case_id}/{document_id}/{page_number:04d}.png"


def extension_for_mime(mime_type: str) -> str:
    """Return the file extension conventionally used for ``mime_type``."""
    return {
        "application/pdf": "pdf",
        "image/jpeg": "jpg",
        "image/png": "png",
    }.get(mime_type, "bin")


def sha256_hex(data: bytes) -> str:
    """Return the lowercase hex SHA-256 digest of ``data`` (B4)."""
    return hashlib.sha256(data).hexdigest()


def storage_path(storage_root: str, storage_key: str) -> Path:
    """Resolve ``storage_key`` under ``storage_root``.

    Raises:
        ValueError: if the resolved path would escape ``storage_root``. Storage
            keys are generated by this module, never by client input, but the
            check stays cheap insurance against a future caller mistake.
    """
    root = Path(storage_root).resolve()
    candidate = (root / storage_key).resolve()
    if root not in candidate.parents and candidate != root:
        raise ValueError("storage key escapes the storage root")
    return candidate


def write_bytes(storage_root: str, storage_key: str, data: bytes) -> Path:
    """Write ``data`` under ``storage_root`` at ``storage_key``, creating dirs."""
    path = storage_path(storage_root, storage_key)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return path


def read_bytes(storage_root: str, storage_key: str) -> bytes:
    """Read bytes previously written by :func:`write_bytes`."""
    return storage_path(storage_root, storage_key).read_bytes()
