"""Identifier generation (spec/backend.md B7, B9).

Public IDs are opaque strings generated by backend code, never by model text or
array position (B7). Every entity family gets a short prefix plus ten lowercase
hex characters, which keeps them globally unique and safe to place in URLs.

Subject IDs are the deliberate exception: they are case-scoped, human-readable
and stable across revisions (``invoice_0001``) because preparers and reviewers
read them in findings (B6, B7).
"""

from __future__ import annotations

import secrets
from typing import Final

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.domain.enums import SubjectType

#: Number of hex characters after the prefix.
ID_RANDOM_LENGTH: Final[int] = 10

USER_PREFIX: Final[str] = "USR_"
SESSION_PREFIX: Final[str] = "SES_"
CASE_PREFIX: Final[str] = "CASE_"
DOCUMENT_PREFIX: Final[str] = "DOC_"
PAGE_PREFIX: Final[str] = "PAGE_"
FACT_PREFIX: Final[str] = "FACT_"
ANALYSIS_PREFIX: Final[str] = "RUN_"
FINDING_PREFIX: Final[str] = "FND_"
JOB_PREFIX: Final[str] = "JOB_"
EXPORT_PREFIX: Final[str] = "EXP_"
SUBMISSION_PREFIX: Final[str] = "SUB_"
EVENT_PREFIX: Final[str] = "EVT_"
RECIPIENT_PREFIX: Final[str] = "RCP_"
RESPONSE_PREFIX: Final[str] = "RESP_"

#: Every prefix the API may emit. Used for validation and documentation.
ID_PREFIXES: Final[tuple[str, ...]] = (
    USER_PREFIX,
    SESSION_PREFIX,
    CASE_PREFIX,
    DOCUMENT_PREFIX,
    PAGE_PREFIX,
    FACT_PREFIX,
    ANALYSIS_PREFIX,
    FINDING_PREFIX,
    JOB_PREFIX,
    EXPORT_PREFIX,
    SUBMISSION_PREFIX,
    EVENT_PREFIX,
    RECIPIENT_PREFIX,
    RESPONSE_PREFIX,
)

#: Zero-padding width for case-scoped subject sequences (``invoice_0001``).
SUBJECT_SEQUENCE_WIDTH: Final[int] = 4


def new_id(prefix: str) -> str:
    """Return a fresh opaque public ID for ``prefix``.

    Args:
        prefix: One of the module-level ``*_PREFIX`` constants.

    Returns:
        ``prefix`` followed by ten lowercase hex characters.

    Raises:
        ValueError: when ``prefix`` is not a known entity prefix.
    """
    if prefix not in ID_PREFIXES:
        raise ValueError(f"Unknown identifier prefix: {prefix!r}")
    return f"{prefix}{secrets.token_hex(ID_RANDOM_LENGTH // 2)}"


def has_prefix(value: str, prefix: str) -> bool:
    """Return True when ``value`` looks like an ID minted with ``prefix``."""
    if not value.startswith(prefix):
        return False
    suffix = value[len(prefix) :]
    return len(suffix) == ID_RANDOM_LENGTH and all(
        character in "0123456789abcdef" for character in suffix
    )


def next_subject_id(session: Session, case_id: str, subject_type: SubjectType) -> str:
    """Allocate the next case-scoped subject ID for ``subject_type``.

    Subject identity must persist across case revisions and same-subject
    replacements (spec/backend.md B7), so sequences are allocated per
    ``(case_id, subject_type)`` and never reused within a case.

    The row lock on the case makes concurrent allocation safe: two workers
    handling the same case serialise on the case row before reading the current
    maximum sequence. The caller owns the surrounding transaction.

    Args:
        session: Open session inside a transaction.
        case_id: Owning case public ID.
        subject_type: Subject family being allocated.

    Returns:
        ``f"{subject_type}_{sequence:04d}"``, e.g. ``invoice_0001``.
    """
    from app.models.case import Case
    from app.models.subject import Subject

    # Serialise allocation for this case; SELECT ... FOR UPDATE on the parent row
    # avoids a unique-violation race on (case_id, sequence, subject_type).
    session.execute(select(Case.id).where(Case.id == case_id).with_for_update())

    current_max: int | None = session.scalar(
        select(func.max(Subject.sequence)).where(
            Subject.case_id == case_id,
            Subject.subject_type == subject_type,
        )
    )
    sequence = (current_max or 0) + 1
    return format_subject_id(subject_type, sequence)


def format_subject_id(subject_type: SubjectType, sequence: int) -> str:
    """Render a case-scoped subject ID from its type and sequence number."""
    if sequence < 1:
        raise ValueError("Subject sequence numbers start at 1")
    return f"{subject_type.value}_{sequence:0{SUBJECT_SEQUENCE_WIDTH}d}"
